import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_component/Header";
import { HistoryHeader } from "./_component/HistoryHeader";
import { Container } from "./_component/Container";
import { CreateUser } from "@/components/createUser";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        ></body>
      </html>

      <div className="w-screen h-screen flex flex-col bg-white justify-center items-center">
        <div className="w-[1440px] h-screen">
          <CreateUser />
          <Header />
          {children}
        </div>
      </div>
    </ClerkProvider>
  );
}
